POUR_LEVELS = {"high":1, "medium": 1, "low": 1.105}
POUR_SPEED = {"high":300, "medium": 225, "low": 200}
X_OFFSET = {"high": 0.08, "medium": 0.07, "low": 0.04} 

BLUE_CUP_FILE = 'files/blue_cup.glb'
RED_CUP_FILE = 'files/red_cup.glb'
WHITE_CUP_FILE = 'files/cup.obj'

# t
CUP_SHELF_X_OFFSET  = -0.25
CUP_SHELF_Y_OFFSET = -0.6

TARGET_CUP_START_POS = (0.55 + CUP_SHELF_X_OFFSET, CUP_SHELF_Y_OFFSET, 0.6) # 0.55 + CUP_SHELF_X_OFFSET
TARGET_CUP_HEIGHT = 0.12 
TARGET_CUP_RADIUS = 0.03
TARGET_CUP_SCALE = 0.028

LEFT_CUP_START_POS = (TARGET_CUP_START_POS[0] - 0.15, CUP_SHELF_Y_OFFSET, 0.5)
RIGHT_CUP_START_POS = (TARGET_CUP_START_POS[0] + 0.15, CUP_SHELF_Y_OFFSET, 0.5)

CUP_HEIGHT = 0.1
CUP_RADIUS = 0.03
CUP_SCALE = 0.025

LIQUID_RADIUS = 0.02
LIQUID_HEIGHT = 0.02

ROD_HEIGHT = 0.2
ROD_RADIUS = 0.005
ROD_START_POS = (TARGET_CUP_START_POS[0] - 0.25, TARGET_CUP_START_POS[1], TARGET_CUP_START_POS[2] + (ROD_HEIGHT / 2))

LIFT_HEIGHT = 0.4

CAM_POS = (0.55 + CUP_SHELF_X_OFFSET, CUP_SHELF_Y_OFFSET - 1.0, 0.5)

POUR_LOCATION = (TARGET_CUP_START_POS[0] - 0.08, 0, LIFT_HEIGHT)
LEFT_POUR_LOC_X = TARGET_CUP_START_POS[0] + 0.08
RIGHT_POUR_LOC_X = TARGET_CUP_START_POS[0] - 0.08

BLUE = (0.3, 0.3, 1.0)
RED = (1.0, 0.4, 0.4)